import type { RetraceEvent } from "../../schema.js";
import type { CheckFinding, CheckRule, Severity } from "../types.js";
import { bashCommand, normalizePath, SHELL_TOOL_NAMES } from "../toolInput.js";

const MAX_DETAIL_LENGTH = 120;
/**
 * Hard ceiling on findings this rule emits per session. Real corpora contain
 * sessions with dozens of shell mutations of the same handful of shapes; an
 * unbounded rule can't be attached to a PR (module 06). When the cap is hit,
 * the last slot becomes a summary finding instead of an individual one, so
 * the rule's own output never exceeds this number.
 */
const MAX_FINDINGS_PER_SESSION = 10;

function truncate(text: string): string {
  const oneLine = text.replace(/\s+/g, " ").trim();
  return oneLine.length > MAX_DETAIL_LENGTH
    ? `${oneLine.slice(0, MAX_DETAIL_LENGTH - 1)}…`
    : oneLine;
}

/**
 * Path segments that mark a location as build/scratch output rather than
 * tracked source. `.retrace` is this tool's own app-data directory (session
 * store, notes cache) — the same class of noise as `.git` for this
 * particular project, not a general-purpose exclusion.
 */
const TRANSIENT_PATH_SEGMENTS = /(^|\/)(node_modules|dist|\.git|\.retrace|tmp|temp|scratch|scratchpad)(\/|$)/;
/** A filename that announces itself as scratch output (`scratch-dump.mjs`, `scratch_export.html`), even sitting loose in a tracked directory. */
const SCRATCH_FILENAME = /^scratch[-_.]/;
/** TypeScript's own incremental-build cache — regenerated by the next `tsc` run, the same class of noise as `dist/`. */
const TRANSIENT_FILENAME_EXTENSIONS = /\.tsbuildinfo$/;

function isTransientPath(path: string): boolean {
  const normalized = normalizePath(path);
  if (TRANSIENT_PATH_SEGMENTS.test(normalized)) return true;
  const filename = normalized.slice(normalized.lastIndexOf("/") + 1);
  return SCRATCH_FILENAME.test(filename) || TRANSIENT_FILENAME_EXTENSIONS.test(filename);
}

function stripQuotes(token: string): string {
  if (token.length >= 2) {
    const first = token[0];
    const last = token[token.length - 1];
    if ((first === '"' && last === '"') || (first === "'" && last === "'")) {
      return token.slice(1, -1);
    }
  }
  return token;
}

/**
 * An unexpanded shell/PowerShell variable reference (`$f`, `$RETRACE_HOME`,
 * `${TMPDIR}/x`, `$env:TEMP\x`) names whatever the variable holds at
 * runtime — this rule reads command text, not a shell, so it never knows
 * that value. Reporting the token itself as the finding's `path` (as a
 * literal file named `$f`) is exactly the "wrongly attributed" failure mode
 * the plan calls out: it looks resolved but names nothing a reviewer can
 * open. Bail out to `undefined` instead, same as any other unresolvable
 * target.
 */
function isUnexpandedVariable(text: string): boolean {
  return /^\$/.test(text);
}

// A `\S+`-style token match has no notion of "end of this shell argument" —
// when the next construct isn't separated by whitespace (`2>/dev/null;`,
// `2>/dev/null)`), trailing shell metacharacters ride along and defeat an
// exact-match check like the null-sink test below. They're never
// legitimately part of an unquoted path in this rule's shapes.
function stripTokenPunctuation(token: string): string | undefined {
  const stripped = stripQuotes(token).trim().replace(/[;)}&|]+$/, "");
  return stripped.length > 0 ? stripped : undefined;
}

function cleanPath(token: string | undefined): string | undefined {
  if (token === undefined) return undefined;
  const stripped = stripTokenPunctuation(token);
  if (stripped === undefined || isUnexpandedVariable(stripped)) return undefined;
  return stripped;
}

/** Simple whitespace tokenizer that keeps `"quoted"` / `'quoted'` spans intact. */
function tokenize(text: string): string[] {
  const tokens: string[] = [];
  const re = /"[^"]*"|'[^']*'|\S+/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(text))) tokens.push(match[0]);
  return tokens;
}

/**
 * Null sinks a redirect can never meaningfully "mutate" — POSIX's
 * `/dev/null`, Windows's `NUL`, and PowerShell's `$null`. Redirecting into
 * one of these is the single most common shape in the measured corpus
 * (`2>/dev/null` to silence stderr on a command that isn't otherwise a
 * mutation) and was previously indistinguishable from a real file write.
 */
function isNullSink(target: string): boolean {
  return /^(\/dev\/null|nul|\$null)$/i.test(target);
}

/**
 * Blanks out `"..."` / `'...'` spans (same length, so later index math
 * stays valid) so an operator quoted as literal text isn't mistaken for a
 * real one. The double-quoted alternative treats `\x` as a single escaped
 * unit (so an escaped `\"`, e.g. inside a `python -c "..."` one-liner that
 * itself contains double-quoted strings, doesn't end the span early) —
 * without that, a stray `"` deep inside an escaped inline script leaves the
 * remainder of the argument unblanked, and whatever `>` happens to appear
 * in it (an HTML tag, a comparison) reads as a real redirect. Single-quoted
 * spans don't support backslash escapes in POSIX shell, so that half stays
 * simple.
 */
function blankQuotedSpans(text: string): string {
  return text.replace(/"(?:\\.|[^"\\])*"|'[^']*'/g, (m) => " ".repeat(m.length));
}

/**
 * Blanks out heredoc bodies (`<<'EOF' ... EOF`, `<<-PY ... PY`),
 * length-preserved with spaces, so embedded script content — JS, Python,
 * arbitrary text piped into a file — never gets scanned as a shell
 * statement of its own. `statementSegments` below splits on newlines, so
 * without this, a heredoc body line like `if count >= 8:` or `if (x >
 * 100000)` reads as its own bare `>` redirect once the heredoc's real
 * opening statement (which may have no redirect at all, e.g. `python - <<
 * 'PY'`) has already been checked and found not to match anything itself.
 * Only the body between the operator and the terminator line is blanked;
 * the opening line (which may carry a real `cat > file <<EOF` redirect) is
 * left untouched.
 */
function stripHeredocBodies(command: string): string {
  const lines = command.split("\n");
  const startRe = /<<-?~?\s*(['"]?)(\w+)\1/;
  let terminator: string | null = null;
  for (let i = 0; i < lines.length; i++) {
    if (terminator !== null) {
      if (lines[i].trim() === terminator) {
        terminator = null;
      } else {
        lines[i] = " ".repeat(lines[i].length);
      }
      continue;
    }
    // Deliberately matched against the raw line, not the quote-blanked one —
    // the delimiter itself is usually quoted (`<<'EOF'`), which is exactly
    // the text this needs to read.
    const match = startRe.exec(lines[i]);
    if (match) terminator = match[2];
  }
  return lines.join("\n");
}

/**
 * Blanks a bash comment (`# ...` to end of line), length-preserved, when
 * the `#` isn't inside quotes and is either at the start of the line or
 * preceded by whitespace (a mid-word `#`, e.g. `foo#bar`, isn't a comment
 * marker to bash either, so it's left alone). Descriptive comments written
 * around a command routinely contain a stray `>` — a placeholder like
 * `<tarball>`, an arrow, a comparison in prose — that reads exactly like a
 * shell redirect once nothing strips the comment text out first.
 */
function stripLineComment(line: string): string {
  const match = /(^|\s)#/.exec(blankQuotedSpans(line));
  if (!match) return line;
  const hashIndex = match.index + match[1].length;
  return line.slice(0, hashIndex) + " ".repeat(line.length - hashIndex);
}

function stripComments(command: string): string {
  return command.split("\n").map(stripLineComment).join("\n");
}

/**
 * Joins a POSIX backslash line-continuation (`\` immediately before a
 * newline) into its following line, length-preserved with spaces. Without
 * this, a multi-line command like `rm -f a.txt \` + newline + `b.txt` reads
 * as two statements once split on newlines below — leaving a dangling `\`
 * to be picked up as a bogus path token, and `b.txt` invisible to `rm`'s
 * argument scan entirely.
 */
function joinLineContinuations(text: string): string {
  return text.replace(/\\\r?\n/g, (m) => " ".repeat(m.length));
}

/** Whether a segment contains a genuine file-writing redirect, and its target if resolvable. */
interface RedirectionMatch {
  matched: boolean;
  path?: string;
}

/**
 * Finds a genuine file-writing redirect: `>`/`>>`, optionally preceded by a
 * file descriptor number, whose target is neither a stream merge (`2>&1`,
 * `>&2`) nor a null sink. Plain `fd>file` (e.g. `2>err.log`, a *real* stderr
 * log) still counts — only the merge/null forms are noise.
 *
 * Operator positions are located in the quote-blanked copy (so a `>` that's
 * really just characters inside a quoted string, e.g. `echo "a > b"`, is
 * skipped), but the target itself is re-read from the *original* command
 * through `tokenize` — which does respect quotes — so a legitimately quoted
 * target like `> "release notes.md"` still resolves correctly.
 *
 * A null sink or stream merge means "keep scanning this segment" — a real
 * redirect may still follow (`cmd 2>/dev/null > out.txt`). An unexpanded
 * variable target (`> "$TEMP/x.js"`) is different: it's *matched*, but
 * unresolvable — that's returned immediately as `{ matched: true, path:
 * undefined }` rather than falling through to keep scanning. Falling
 * through here used to be how a heredoc body got misread: `cat >
 * "$TEMP/x.js" <<'EOF'` followed by JS containing `if (x > 100000)` would
 * skip the (then-rejected) `$TEMP/x.js` target and keep hunting, latching
 * onto `100000` from inside the heredoc as if it were a shell redirect
 * target. Stopping at the first real operator, resolved or not, keeps the
 * scan inside the actual redirect the command wrote.
 */
function findRedirectionTarget(command: string): RedirectionMatch {
  const scanned = blankQuotedSpans(command);
  const re = /\d*>{1,2}/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(scanned))) {
    const afterOperator = command.slice(match.index + match[0].length);
    const targetToken = tokenize(afterOperator)[0];
    if (targetToken === undefined) continue;
    if (targetToken.startsWith("&")) continue; // stream merge, e.g. 2>&1 / >&2
    const stripped = stripTokenPunctuation(targetToken);
    if (stripped === undefined || isNullSink(stripped)) continue;
    return { matched: true, path: isUnexpandedVariable(stripped) ? undefined : stripped };
  }
  return { matched: false };
}

/**
 * Splits a command into independent statement segments on newlines, `&&`,
 * `||`, and `;` (not `|` — a pipeline's tail, e.g. `foo | tee out.log`, is
 * one statement for this rule's purposes). Real sessions routinely pass a
 * whole multi-step script as a single Bash `command` string (verification
 * scripts, heredocs); without this, a keyword match on one line would greedily
 * consume argument text from an unrelated later line — e.g. `rm a.ts\ncd
 * repo && pnpm test` previously resolved `rm`'s target as `repo`, from the
 * `cd` on the *next* line, because nothing stopped the scan at the newline.
 * Each segment is matched against `MUTATION_SHAPES` independently, and a
 * shape's arguments are only ever read from its own segment.
 */
function statementSegments(command: string): string[] {
  const scanned = blankQuotedSpans(command);
  const segments: string[] = [];
  let start = 0;
  const stopRe = /\n|&&|\|\||;/g;
  let match: RegExpExecArray | null;
  while ((match = stopRe.exec(scanned))) {
    segments.push(command.slice(start, match.index));
    start = match.index + match[0].length;
  }
  segments.push(command.slice(start));
  return segments;
}

/** Where a shape's own argument scan should stop within its segment — an unrelated trailing redirect, e.g. the `> log.txt` in `cp a.ts b.ts > log.txt`. */
const ARGS_STOP = /\d*>{1,2}/;

/** The segment text following `pattern`'s match, cut off at a trailing redirect so unrelated shell syntax doesn't bleed in. */
function argsAfterMatch(segment: string, pattern: RegExp): string | undefined {
  const match = pattern.exec(blankQuotedSpans(segment));
  if (!match) return undefined;
  const rest = segment.slice(match.index + match[0].length);
  const stop = rest.search(ARGS_STOP);
  return stop === -1 ? rest : rest.slice(0, stop);
}

/** POSIX-style argument scan: strip `-flag` tokens (none of this rule's POSIX shapes take a separate value token), return the first or last remaining positional. */
function posixPositional(argsText: string, position: "first" | "last"): string | undefined {
  const positionals = tokenize(argsText).filter((t) => !t.startsWith("-"));
  if (positionals.length === 0) return undefined;
  return cleanPath(position === "first" ? positionals[0] : positionals[positionals.length - 1]);
}

/** These name the file target; their value is the resolved path. */
const POWERSHELL_PATH_FLAGS = new Set(["-path", "-literalpath", "-filepath", "-destination"]);
/**
 * These take a following value too, but it isn't a path — `-Encoding ascii`,
 * `-Value "text"`. Without knowing this, `ascii`/`"text"` would be mistaken
 * for a bare positional argument (the flag's own dash makes it obviously not
 * one, but its *value* token doesn't start with `-`, so it looks exactly
 * like one) once the scan moves past the flag.
 */
const POWERSHELL_OTHER_VALUE_FLAGS = new Set([
  "-value",
  "-itemtype",
  "-encoding",
  "-delimiter",
  "-erroraction",
]);

/**
 * PowerShell-style argument scan: named flags that take a following value
 * consume it (so its value never gets mistaken for a bare positional
 * argument — see `POWERSHELL_OTHER_VALUE_FLAGS`); an explicit
 * `-Path`/`-LiteralPath`/`-FilePath`/`-Destination` wins outright when
 * present, since that's what PowerShell scripts actually use to name the
 * target. Only known value-taking flags are special-cased — an unrecognized
 * `-Flag` is assumed boolean (like `-Recurse`/`-Force`) and its neighbor is
 * left as a candidate positional.
 */
function powerShellPositional(argsText: string, position: "first" | "last"): string | undefined {
  const tokens = tokenize(argsText);
  const positionals: string[] = [];
  let preferred: string | undefined;
  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (token.startsWith("-")) {
      const key = token.toLowerCase();
      const value = tokens[i + 1];
      const isPathFlag = POWERSHELL_PATH_FLAGS.has(key);
      if ((isPathFlag || POWERSHELL_OTHER_VALUE_FLAGS.has(key)) && value !== undefined) {
        if (isPathFlag) {
          if (key === "-destination") preferred = value;
          else preferred ??= value;
        }
        i++;
      }
      continue;
    }
    positionals.push(token);
  }
  if (preferred !== undefined) return cleanPath(preferred);
  if (positionals.length === 0) return undefined;
  return cleanPath(position === "first" ? positionals[0] : positionals[positionals.length - 1]);
}

type ExtractMode = "redirection" | "posix-first" | "posix-last" | "powershell-first" | "powershell-last" | "none";

interface MutationShape {
  label: string;
  pattern: RegExp;
  extract: ExtractMode;
  /**
   * Near-universal housekeeping: creating a directory, installing a
   * dependency, or reverting to tracked state are expected agent activity,
   * not a gap in Retrace's record worth a reviewer's attention — so these
   * fall to `low` rather than `medium` when (as is essentially always the
   * case) no single file target applies. `extract: "none"` here is
   * deliberate, not a placeholder: a resolvable target for these shapes
   * (a branch name, a ref, a package specifier) isn't a file path, and
   * guessing one risks the "wrongly attributed" failure mode the path
   * extraction is built to avoid.
   */
  housekeeping?: boolean;
}

/**
 * Conservative shapes of a shell command that write to the filesystem —
 * both POSIX/Bash ones and PowerShell's native cmdlets, since this project
 * develops on Windows and real sessions run PowerShell about as often as a
 * POSIX shell (`rm`/`cp`/`mv`/`mkdir` are also PowerShell's builtin aliases,
 * so those patterns already cover both). Ordered list (not a set) so a
 * command matching several shapes is attributed to the first, most specific
 * one it hits.
 */
const MUTATION_SHAPES: MutationShape[] = [
  { label: "sed -i", pattern: /\bsed\s+(?:-\w*i\w*|--in-place)\b/, extract: "posix-last" },
  {
    label: "git checkout/reset/apply/revert",
    pattern: /\bgit\s+(?:checkout|reset|apply|revert)\b/,
    extract: "none",
    housekeeping: true,
  },
  {
    label: "package install",
    pattern: /\b(?:npm|pnpm|yarn)\s+(?:install|i|ci|add|remove|uninstall)\b/,
    extract: "none",
    housekeeping: true,
  },
  { label: "Remove-Item", pattern: /\bRemove-Item\b/i, extract: "powershell-last" },
  { label: "Copy-Item", pattern: /\bCopy-Item\b/i, extract: "powershell-last" },
  { label: "Move-Item", pattern: /\bMove-Item\b/i, extract: "powershell-last" },
  { label: "New-Item", pattern: /\bNew-Item\b/i, extract: "powershell-last" },
  {
    label: "Set-Content / Add-Content / Out-File",
    pattern: /\b(?:Set-Content|Add-Content|Out-File)\b/i,
    extract: "powershell-first",
  },
  { label: "mv", pattern: /\bmv\b/, extract: "posix-last" },
  { label: "cp", pattern: /\bcp\b/, extract: "posix-last" },
  { label: "rm", pattern: /\brm\b/, extract: "posix-last" },
  { label: "mkdir", pattern: /\bmkdir\b/, extract: "none", housekeeping: true },
  { label: "touch", pattern: /\btouch\b/, extract: "posix-last" },
  { label: "patch", pattern: /\bpatch\b/, extract: "none" },
  { label: "tee", pattern: /\btee\b/, extract: "posix-last" },
  {
    label: "output redirection (> / >>)",
    // The authoritative check is `findRedirectionTarget` above (this pattern
    // is kept only for documentation) — a bare `>` also matches noise like
    // `2>/dev/null` and `2>&1`, which is exactly what this module fixes.
    pattern: />{1,2}/,
    extract: "redirection",
  },
];

function matchingShapeInSegment(segment: string): { shape: MutationShape; path: string | undefined } | undefined {
  for (const shape of MUTATION_SHAPES) {
    if (shape.extract === "redirection") {
      const redirect = findRedirectionTarget(segment);
      if (redirect.matched) return { shape, path: redirect.path };
      continue;
    }
    if (!shape.pattern.test(segment)) continue;

    const path = ((): string | undefined => {
      switch (shape.extract) {
        case "posix-first": {
          const rest = argsAfterMatch(segment, shape.pattern);
          return rest !== undefined ? posixPositional(rest, "first") : undefined;
        }
        case "posix-last": {
          const rest = argsAfterMatch(segment, shape.pattern);
          return rest !== undefined ? posixPositional(rest, "last") : undefined;
        }
        case "powershell-first": {
          const rest = argsAfterMatch(segment, shape.pattern);
          return rest !== undefined ? powerShellPositional(rest, "first") : undefined;
        }
        case "powershell-last": {
          const rest = argsAfterMatch(segment, shape.pattern);
          return rest !== undefined ? powerShellPositional(rest, "last") : undefined;
        }
        case "none":
        default:
          return undefined;
      }
    })();
    return { shape, path };
  }
  return undefined;
}

/**
 * Finds the first shape a command matches, scanning statement by statement
 * (see `statementSegments`) so a shape's arguments are only ever read from
 * the same statement its keyword appeared in.
 */
function matchingShape(command: string): { shape: MutationShape; path: string | undefined } | undefined {
  for (const segment of statementSegments(stripHeredocBodies(stripComments(joinLineContinuations(command))))) {
    const found = matchingShapeInSegment(segment);
    if (found) return found;
  }
  return undefined;
}

function severityFor(shape: MutationShape, resolvedPath: string | undefined): Severity {
  if (resolvedPath !== undefined) return isTransientPath(resolvedPath) ? "low" : "medium";
  return shape.housekeeping ? "low" : "medium";
}

/**
 * A `Bash` or `PowerShell` command matched a filesystem-mutation shape. This
 * is the only rule here that isn't NLP-heuristic — it's a structural fact
 * about the system, not the transcript: Claude Code's PreToolUse hook (and
 * this historical parser) only ever synthesize `file_change` events for
 * Write/Edit/NotebookEdit tool calls, never for a shell tool, so a mutating
 * shell command is *always* absent from the working-tree reconstruction. The
 * `file_change` check below is therefore mostly documentation of that fact
 * (and a guard against it silently changing later) rather than a filter that
 * currently excludes anything.
 */
export const untrackedBashMutationRule: CheckRule = {
  id: "untracked-bash-mutation",
  description:
    "A Bash or PowerShell command matched a filesystem-mutation shape (redirection, sed -i, mv/cp/rm, Remove-Item, git checkout/reset, package install, ...) with no corresponding file_change event — these changes are outside Retrace's record, and also outside Claude Code's own /rewind, which does not track files modified by shell commands either. Excludes stderr-to-null and stream-merge redirects (2>/dev/null, 2>&1), names the target file when it can be resolved from the command text (never guessing at an unexpanded shell variable), and collapses to one finding per distinct (shape, resolved file) pair per session — except for a transient location (node_modules/, dist/, .git/, .retrace/, temp dirs, *.tsbuildinfo), which collapses by shape alone, same as housekeeping shapes with no resolvable target. Capped at 10 findings per session with a trailing summary of any remainder.",
  defaultSeverity: "medium",
  run(events: RetraceEvent[]): CheckFinding[] {
    const fileChangeToolUseIds = new Set(
      events
        .filter((e): e is Extract<RetraceEvent, { kind: "file_change" }> => e.kind === "file_change")
        .map((e) => e.payload.toolUseId)
        .filter((id): id is string => id !== undefined),
    );

    const seen = new Map<string, CheckFinding>();

    for (const event of events) {
      if (event.kind !== "tool_call" || !SHELL_TOOL_NAMES.has(event.payload.toolName)) continue;
      const command = bashCommand(event.payload.input);
      if (!command) continue;
      if (fileChangeToolUseIds.has(event.payload.toolUseId)) continue;

      const match = matchingShape(command);
      if (!match) continue;
      const { shape, path } = match;

      // Per-(shape, path) granularity is for paths worth a reviewer's individual
      // attention. A transient path (scratch/log/temp output) isn't a project
      // file the way step 4's "two different files touched by cp" example means
      // — ten different scratch-file writes of the same shape are exactly the
      // "ten mkdir calls" case, not ten distinct findings, so those collapse by
      // shape alone, same as an unresolved path.
      const distinguishable = path !== undefined && !isTransientPath(path);
      const groupKey = `${shape.label} ${distinguishable ? normalizePath(path) : ""}`;
      if (seen.has(groupKey)) continue;

      const severity = severityFor(shape, path);
      const title = path
        ? `${path} may have been modified by a shell command, outside Retrace's record`
        : `${event.payload.toolName} command (${shape.label}) may have modified files outside Retrace's record`;

      seen.set(groupKey, {
        ruleId: "untracked-bash-mutation",
        severity,
        title,
        detail: truncate(command),
        seq: event.seq,
        path,
        toolUseId: event.payload.toolUseId,
        sidechain: event.sidechain === true ? true : undefined,
      });
    }

    const findings = [...seen.values()];
    if (findings.length <= MAX_FINDINGS_PER_SESSION) return findings;

    const kept = findings.slice(0, MAX_FINDINGS_PER_SESSION - 1);
    const overflow = findings.length - kept.length;
    kept.push({
      ruleId: "untracked-bash-mutation",
      severity: "low",
      title: `${overflow} more untracked-bash-mutation finding(s) in this session were suppressed (capped at ${MAX_FINDINGS_PER_SESSION})`,
      seq: findings[kept.length].seq,
    });
    return kept;
  },
};
